corrected subdirectories

diff --git a/Osi/configure b/Osi/configure
--- a/Osi/configure
+++ b/Osi/configure
@@ -473,7 +473,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE COIN_DEBUG_TRUE COIN_DEBUG_FALSE CXXDEFS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake BUILDTOOLSDIR AUX_DIR HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE MAINTAINER_SMALL_TRUE MAINTAINER_SMALL_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL pkg_lib_dir pkg_include_dir pkg_bin_dir CBCSRCDIR CBCOBJDIR COIN_HAS_CBC_TRUE COIN_HAS_CBC_FALSE CLPSRCDIR CLPOBJDIR COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE COINBASESRCDIR COINBASEOBJDIR COIN_HAS_COINBASE_TRUE COIN_HAS_COINBASE_FALSE DYLPSRCDIR DYLPOBJDIR COIN_HAS_DYLP_TRUE COIN_HAS_DYLP_FALSE SYMSRCDIR SYMOBJDIR COIN_HAS_SYM_TRUE COIN_HAS_SYM_FALSE VOLSRCDIR VOLOBJDIR COIN_HAS_VOL_TRUE COIN_HAS_VOL_FALSE CPXINCDIR CPXLIBDIR COIN_HAS_CPX_TRUE COIN_HAS_CPX_FALSE GLPKINCDIR GLPKLIBDIR COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE FMPINCDIR FMPLIBDIR COIN_HAS_FMP_TRUE COIN_HAS_FMP_FALSE MSKINCDIR MSKLIBDIR COIN_HAS_MSK_TRUE COIN_HAS_MSK_FALSE OSLINCDIR OSLLIBDIR COIN_HAS_OSL_TRUE COIN_HAS_OSL_FALSE SPXINCDIR SPXLIBDIR COIN_HAS_SPX_TRUE COIN_HAS_SPX_FALSE XPRINCDIR XPRLIBDIR COIN_HAS_XPR_TRUE COIN_HAS_XPR_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE COIN_DEBUG_TRUE COIN_DEBUG_FALSE CXXDEFS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake BUILDTOOLSDIR AUX_DIR HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE MAINTAINER_SMALL_TRUE MAINTAINER_SMALL_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL pkg_lib_dir pkg_include_dir pkg_bin_dir CBCSRCDIR CBCOBJDIR COIN_HAS_CBC_TRUE COIN_HAS_CBC_FALSE CLPSRCDIR CLPOBJDIR COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE COINBASESRCDIR COINBASEOBJDIR COIN_HAS_COINBASE_TRUE COIN_HAS_COINBASE_FALSE DYLPSRCDIR DYLPOBJDIR COIN_HAS_DYLP_TRUE COIN_HAS_DYLP_FALSE OSISRCDIR OSIOBJDIR COIN_HAS_OSI_TRUE COIN_HAS_OSI_FALSE SYMSRCDIR SYMOBJDIR COIN_HAS_SYM_TRUE COIN_HAS_SYM_FALSE VOLSRCDIR VOLOBJDIR COIN_HAS_VOL_TRUE COIN_HAS_VOL_FALSE CPXINCDIR CPXLIBDIR COIN_HAS_CPX_TRUE COIN_HAS_CPX_FALSE GLPKINCDIR GLPKLIBDIR COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE FMPINCDIR FMPLIBDIR COIN_HAS_FMP_TRUE COIN_HAS_FMP_FALSE MSKINCDIR MSKLIBDIR COIN_HAS_MSK_TRUE COIN_HAS_MSK_FALSE OSLINCDIR OSLLIBDIR COIN_HAS_OSL_TRUE COIN_HAS_OSL_FALSE SPXINCDIR SPXLIBDIR COIN_HAS_SPX_TRUE COIN_HAS_SPX_FALSE XPRINCDIR XPRLIBDIR COIN_HAS_XPR_TRUE COIN_HAS_XPR_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -19555,7 +19555,7 @@ _ACEOF
 
   CBCSRCDIR=`cd $srcdir/$coin_has_cbc; pwd`
 
-  CBCOBJDIR=`pwd`/$coin_has_cbc
+  CBCOBJDIR=`cd $coin_has_cbc; pwd`
 fi
 
   # Define the Makefile conditional
@@ -19599,7 +19599,7 @@ _ACEOF
 
   CLPSRCDIR=`cd $srcdir/$coin_has_clp; pwd`
 
-  CLPOBJDIR=`pwd`/$coin_has_clp
+  CLPOBJDIR=`cd $coin_has_clp; pwd`
 fi
 
   # Define the Makefile conditional
@@ -19643,7 +19643,7 @@ _ACEOF
 
   COINBASESRCDIR=`cd $srcdir/$coin_has_coinbase; pwd`
 
-  COINBASEOBJDIR=`pwd`/$coin_has_coinbase
+  COINBASEOBJDIR=`cd $coin_has_coinbase; pwd`
 fi
 
   # Define the Makefile conditional
@@ -19687,7 +19687,7 @@ _ACEOF
 
   DYLPSRCDIR=`cd $srcdir/$coin_has_dylp; pwd`
 
-  DYLPOBJDIR=`pwd`/$coin_has_dylp
+  DYLPOBJDIR=`cd $coin_has_dylp; pwd`
 fi
 
   # Define the Makefile conditional
@@ -19703,6 +19703,50 @@ fi
 
 echo "$as_me:$LINENO: result: $coin_has_dylp" >&5
 echo "${ECHO_T}$coin_has_dylp" >&6
+
+echo "$as_me:$LINENO: checking for COIN project Osi" >&5
+echo $ECHO_N "checking for COIN project Osi... $ECHO_C" >&6
+
+# First check, if the sub-project is actually available (ToDo: allow
+# other locations)
+
+coin_has_osi=unavailable
+if test $PACKAGE_TARNAME = osi; then
+  coin_has_osi=.
+else
+  if test -d $srcdir/../Osi; then
+    coin_has_osi=../Osi
+  fi
+fi
+
+if test $coin_has_osi != unavailable; then
+  # Set the #define if the component is available
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_OSI 1
+_ACEOF
+
+
+  # Set the variables for source and object code location
+
+  OSISRCDIR=`cd $srcdir/$coin_has_osi; pwd`
+
+  OSIOBJDIR=`cd $coin_has_osi; pwd`
+fi
+
+  # Define the Makefile conditional
+
+
+if test $coin_has_osi != unavailable; then
+  COIN_HAS_OSI_TRUE=
+  COIN_HAS_OSI_FALSE='#'
+else
+  COIN_HAS_OSI_TRUE='#'
+  COIN_HAS_OSI_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_osi" >&5
+echo "${ECHO_T}$coin_has_osi" >&6
 
 echo "$as_me:$LINENO: checking for COIN project Sym" >&5
 echo $ECHO_N "checking for COIN project Sym... $ECHO_C" >&6
@@ -19731,7 +19775,7 @@ _ACEOF
 
   SYMSRCDIR=`cd $srcdir/$coin_has_sym; pwd`
 
-  SYMOBJDIR=`pwd`/$coin_has_sym
+  SYMOBJDIR=`cd $coin_has_sym; pwd`
 fi
 
   # Define the Makefile conditional
@@ -19775,7 +19819,7 @@ _ACEOF
 
   VOLSRCDIR=`cd $srcdir/$coin_has_vol; pwd`
 
-  VOLOBJDIR=`pwd`/$coin_has_vol
+  VOLOBJDIR=`cd $coin_has_vol; pwd`
 fi
 
   # Define the Makefile conditional
@@ -21093,6 +21137,13 @@ echo "$as_me: error: conditional \"COIN_HAS_DYLP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${COIN_HAS_OSI_TRUE}" && test -z "${COIN_HAS_OSI_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_OSI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_OSI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${COIN_HAS_SYM_TRUE}" && test -z "${COIN_HAS_SYM_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_SYM\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -21805,6 +21856,10 @@ s,@DYLPSRCDIR@,$DYLPSRCDIR,;t t
 s,@DYLPOBJDIR@,$DYLPOBJDIR,;t t
 s,@COIN_HAS_DYLP_TRUE@,$COIN_HAS_DYLP_TRUE,;t t
 s,@COIN_HAS_DYLP_FALSE@,$COIN_HAS_DYLP_FALSE,;t t
+s,@OSISRCDIR@,$OSISRCDIR,;t t
+s,@OSIOBJDIR@,$OSIOBJDIR,;t t
+s,@COIN_HAS_OSI_TRUE@,$COIN_HAS_OSI_TRUE,;t t
+s,@COIN_HAS_OSI_FALSE@,$COIN_HAS_OSI_FALSE,;t t
 s,@SYMSRCDIR@,$SYMSRCDIR,;t t
 s,@SYMOBJDIR@,$SYMOBJDIR,;t t
 s,@COIN_HAS_SYM_TRUE@,$COIN_HAS_SYM_TRUE,;t t
